name: Mongo Import Test

on: [push]

jobs:
  test-mongo:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
    steps:
      - uses: actions/checkout@v1
      - name: import data to mongo
        run: |
          export CONTAINER=$(docker ps -aqf "name=mongo")
          docker cp testcol.json $CONTAINER:/tmp/testcol.json
          docker exec $CONTAINER mongoimport -d test -c testcol --file /tmp/testcol.json
      - name: print data from mongo
        run: |
          export CONTAINER=$(docker ps -aqf "name=mongo")
          docker exec $CONTAINER mongoexport -d test -c testcol
